command: /usr/bin/python /home/arigo/pypysrc/pypy/tool/alarm.py 900 /home/arigo/pypysrc/pypy/interpreter/py.py --oldstyle /home/arigo/pypysrc/lib-python-2.3.4/test/test_bsddb185.py
run by: arigo@tismerysoft.de
sys.platform: linux2
sys.version_info: (2, 3, 5, 'final', 0)
startdate: Thu Apr 28 04:59:09 2005
pypy-revision: 11518
============================================================
faking <type 'unicode'>
faking <type 'module'>
faking <type 'file'>
faking <type 'posix.stat_result'>
faking <type 'posix.statvfs_result'>
Traceback (application-level):
  File "/home/arigo/pypysrc/lib-python-2.3.4/test/test_bsddb185.py", line 9 in ?
import bsddb185
ImportError: bsddb185
========================== closed ==========================
execution time: 5.5461909771 seconds
exit status: 1
