command: /usr/bin/python /home/arigo/pypysrc/pypy/tool/alarm.py 900 /home/arigo/pypysrc/pypy/interpreter/py.py --oldstyle /home/arigo/pypysrc/lib-python-2.3.4/test/test_gl.py
run by: arigo@tismerysoft.de
sys.platform: linux2
sys.version_info: (2, 3, 5, 'final', 0)
startdate: Thu Apr 28 01:17:39 2005
pypy-revision: 11518
============================================================
faking <type 'unicode'>
faking <type 'module'>
faking <type 'file'>
faking <type 'posix.stat_result'>
faking <type 'posix.statvfs_result'>
Traceback (application-level):
  File "/home/arigo/pypysrc/lib-python-2.3.4/test/test_gl.py", line 7 in ?
import gl, GL, time
ImportError: gl
========================== closed ==========================
execution time: 5.54836797714 seconds
exit status: 1
