command: /usr/bin/python /home/arigo/pypysrc/pypy/tool/alarm.py 900 /home/arigo/pypysrc/pypy/interpreter/py.py --oldstyle /home/arigo/pypysrc/lib-python-2.3.4/test/test_curses.py
run by: arigo@tismerysoft.de
sys.platform: linux2
sys.version_info: (2, 3, 5, 'final', 0)
startdate: Thu Apr 28 03:15:43 2005
pypy-revision: 11518
============================================================
faking <type 'unicode'>
faking <type 'module'>
faking <type 'file'>
Traceback (application-level):
  File "/home/arigo/pypysrc/lib-python-2.3.4/test/test_curses.py", line 11 in ?
import curses, sys, tempfile
  File "/home/arigo/pypysrc/lib-python-2.3.4/curses/__init__.py", line 15 in ?
from _curses import *
ImportError: _curses
========================== closed ==========================
execution time: 0.982558012009 seconds
exit status: 1
