command: /usr/bin/python /home/arigo/pypysrc/pypy/tool/alarm.py 900 /home/arigo/pypysrc/pypy/interpreter/py.py --oldstyle /home/arigo/pypysrc/lib-python-2.3.4/test/test_atexit.py
run by: arigo@tismerysoft.de
sys.platform: linux2
sys.version_info: (2, 3, 5, 'final', 0)
startdate: Thu Apr 28 05:11:12 2005
pypy-revision: 11518
============================================================
faking <type 'unicode'>
faking <type 'module'>
faking <type 'file'>
faking <type 'posix.stat_result'>
faking <type 'posix.statvfs_result'>
faking <type 'unicode'>
faking <type 'module'>
faking <type 'file'>
Traceback (application-level):
  File "/home/arigo/pypysrc/lib-python-2.3.4/test/test_atexit.py", line 37 in ?
""")
  File "/home/arigo/pypysrc/lib-python-2.3.4/test/test_support.py", line 194 in vereq
        raise TestFailed, "%r == %r" % (a, b)
TestFailed: '' == "handler2 (7,) {'kw': 'abc'}\nhandler2 () {}\nhandler1\n"
========================== closed ==========================
execution time: 7.03922986984 seconds
exit status: 1
