command: /usr/bin/python /u/pedronis/PyPy/dist/pypy/tool/alarm.py 900 /u/pedronis/PyPy/dist/pypy/interpreter/py.py --oldstyle /u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_atexit.py
run by: pedronis@ratthing-b246
sys.platform: linux2
sys.version_info: (2, 3, 5, 'final', 0)
startdate: Wed Apr 27 21:56:42 2005
pypy-revision: 11549
============================================================
faking <type 'unicode'>
faking <type 'module'>
faking <type 'file'>
faking <type 'posix.stat_result'>
faking <type 'posix.statvfs_result'>
faking <type 'unicode'>
faking <type 'module'>
faking <type 'file'>
Traceback (application-level):
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_atexit.py", line 37 in ?
""")
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_support.py", line 194 in vereq
        raise TestFailed, "%r == %r" % (a, b)
TestFailed: '' == "handler2 (7,) {'kw': 'abc'}\nhandler2 () {}\nhandler1\n"
========================== closed ==========================
execution time: 8.41355109215 seconds
exit status: 1
